Source/Urho3D/CMakeLists.txt
Add nativefiledialog entry and seperate lib entries with newlines for clearer git merge compatability
=> CMake: add native file dialog.  

Source/Tools/Editor/CMakeLists.txt
=> Editor: CMake Target Type Tied to URHO3D_WIN32_CONSOLE

Source/Tools/Editor/Tabs/ResourceTab.cpp, Source/Tools/Toolbox/SystemUI/Widgets.cpp, Source/Urho3D/Container/Hash.h, Source/Urho3D/Math/Color.cpp, Source/Urho3D/Math/Color.h
=> Just minor changes

Source/Urho3D/CMakeLists.txt, Source/Urho3D/Core/Context.cpp, Source/Urho3D/Core/Variant.cpp, Source/Urho3D/Core/Variant.h, Source/Urho3D/IO/Deserializer.cpp, Source/Urho3D/IO/Serializer.cpp, Source/Urho3D/Resource/JSONValue.cpp, Source/Urho3D/Resource/XMLElement.cpp, Source/Urho3D/Scene/Serializable.h, script/rbfx.natvis
=> Refactor Variant custom type handling.

Source/Urho3D/CSharp/Managed/Graphics/IndexBuffer.cs, Source/Urho3D/CSharp/Managed/Graphics/VertexBuffer.cs
I have added some methods that is frequently used that will make things more easier during coding
**SaveXML(string path,string Rootnode)**
Saving to file path is not originally provided, so instead of creating XMLfile->create root-> save scene->save File. now all in one save to the string path, and optionally RootName
**RemoveAllChildrenbyName** => remove all children of a specific Name
**RemoveAllComponents** => remove all children of a specific Name
**GetComponentsbyType** =>Get all Components of a specific Type
**VertexBuffer.SetData(float[])**  instead of IntPtr
**IndexBuffer.SetData(float[]) **  instead of IntPtr
the above functions is addition to make query more easy.
Happy Coding :)
=> API Enhancment

Source/Tools/Editor/Tabs/Scene/SceneTab.cpp, Source/Tools/Toolbox/Scene/DebugCameraController.cpp, Source/Tools/Toolbox/Scene/DebugCameraController.h, Source/Tools/Toolbox/SystemUI/Gizmo.cpp, Source/Tools/Toolbox/SystemUI/Gizmo.h
Add some basic shortcut that can be found in most Editors
=> Editor: Add short cut for camera operation and gizmo mode selection

Source/Urho3D/Core/DirtyFlag.h, Source/Urho3D/Core/Mutex.h, Source/Urho3D/Graphics/Camera.cpp, Source/Urho3D/Graphics/Camera.h, Source/Urho3D/Math/MathDefs.h, Source/Urho3D/UI/Text3D.cpp, Source/Urho3D/UI/Text3D.h, Source/Urho3D/UI/TextRenderer3D.cpp, Source/Urho3D/UI/TextRenderer3D.h
- Add TextRenderer3D for immediate-mode text rendering;
- Fix data races in Camera;
- Add caching of view-projection matrices;
- Add Text3D snap to pixels mode.
=> Add TextRenderer3D utility class.

Source/Urho3D/CSharp/Scripts/Compiler.cs
and minor windows related tweaks
I didn't make an Issue. Lemme know if it is needed :)
=> Fix Editor crash on Windows when cs script doesn't compile

Source/Urho3D/CSharp/Managed/Math/Color.cs, Source/Urho3D/CSharp/Managed/Math/IntRect.cs, Source/Urho3D/CSharp/Managed/Math/Rect.cs
Color:
- RGBA components are now publicly available 
- Color modulation with * operator
Rect and IntRect
- Few methods now publicly available. I think these were accidentally made private.
=> Small tweaks in Rect, IntRect and Color to make them more usable

Source/Urho3D/CSharp/Managed/Math/Quaternion.cs
=> Quaternion IDENTITY fixed

Source/Tests/CommonUtils.cpp, Source/Tests/CommonUtils.h, Source/Tests/Engine/Engine.cpp, Source/Urho3D/IO/Log.cpp, Source/Urho3D/IO/Log.h
@rokups please look at this just in case I messed up
=> Fix incorrect logger re-initialization.

Source/Urho3D/Input/FreeFlyController.cpp, Source/Urho3D/Input/FreeFlyController.h
Sorry, I don't know how I forgot about it. Here is a quick fix.
=> Gimbal lock fix

Source/Tests/Graphics/ParticleGraph.cpp, Source/Urho3D/CSharp/Swig/generated/Urho3D/_pre_particles.i, Source/Urho3D/CSharp/Swig/generated/Urho3D/_pre_replica.i, Source/Urho3D/Graphics/Octree.cpp, Source/Urho3D/Particles/ParticleGraphEmitter.cpp, Source/Urho3D/Particles/ParticleGraphEmitter.h, Source/Urho3D/Particles/ParticleGraphLayerInstance.cpp, Source/Urho3D/Particles/ParticleGraphLayerInstance.h, Source/Urho3D/Particles/ParticleGraphPin.h, Source/Urho3D/Replica/ClientReplica.cpp, Source/Urho3D/Replica/ClientReplica.h, Source/Urho3D/Replica/NetworkTime.h
- manual drawable bug fix
- emitting flag
- include path fix
=> Particle effect updates and SoftNetworkTime.Get renaming

Source/Editor/Foundation/SceneViewTab/EditorCamera.cpp, Source/Editor/Foundation/SceneViewTab/EditorCamera.h, Source/Urho3D/SystemUI/ImGui.cpp, Source/Urho3D/SystemUI/ImGui.h
hello, this might be useful for editor. check out
=> add mouse wheel for editor

Source/Editor/Foundation/ResourceBrowserTab.cpp, Source/Urho3D/SystemUI/MaterialInspectorWidget.cpp, Source/Urho3D/SystemUI/SceneHierarchyWidget.cpp, Source/Urho3D/SystemUI/Widgets.cpp
https://github.com/rbfx/rbfx/issues/435
=> SetTooltip fixed

Source/Editor/Editor.cpp, Source/Samples/14_SoundEffects/SoundEffects.cpp, Source/Samples/43_HttpRequestDemo/HttpRequestDemo.cpp, Source/Tests/Container/Ptr.cpp, Source/Urho3D/Container/Ptr.h, Source/Urho3D/Engine/StateManager.cpp, Source/Urho3D/Graphics/Direct3D11/D3D11ComputeDevice.cpp, Source/Urho3D/Graphics/Light.cpp, Source/Urho3D/Resource/JSONValue.cpp, Source/Urho3D/Resource/XMLElement.cpp, Source/Urho3D/RmlUI/RmlCanvasComponent.cpp, Source/Urho3D/RmlUI/RmlEventListeners.cpp, Source/Urho3D/RmlUI/RmlFile.cpp, Source/Urho3D/RmlUI/RmlUIComponent.cpp
=> Support classes not inherited from RefCounted in SharedPtr and WeakPtr.

Source/Editor/Foundation/SceneViewTab/SceneDragAndDropMaterial.cpp, Source/Editor/Foundation/SceneViewTab/SceneDragAndDropPrefab.cpp
=> Fix unneeded physics includes in Editor

Source/Urho3D/Plugins/PluginManager.cpp, Source/Urho3D/Plugins/PluginManager.h, Source/Urho3D/RmlUI/RmlUIComponent.h
Return main plugin. The result is valid after plugin application started.
=> GetMainPlugin

Source/Tests/Navigation/Navigation.cpp, Source/ThirdParty/Detour/Include/Detour/DetourCommon.h, Source/ThirdParty/Detour/Include/Detour/DetourMath.h, Source/ThirdParty/Detour/Include/Detour/DetourNavMesh.h, Source/ThirdParty/Detour/Include/Detour/DetourNavMeshQuery.h, Source/ThirdParty/Detour/Include/Detour/DetourNode.h, Source/ThirdParty/Detour/Source/DetourAlloc.cpp, Source/ThirdParty/Detour/Source/DetourCommon.cpp, Source/ThirdParty/Detour/Source/DetourNavMesh.cpp, Source/ThirdParty/Detour/Source/DetourNavMeshQuery.cpp, Source/ThirdParty/DetourCrowd/Include/DetourCrowd/DetourCrowd.h, Source/ThirdParty/DetourCrowd/Source/DetourCrowd.cpp, Source/ThirdParty/DetourCrowd/Source/DetourLocalBoundary.cpp, Source/ThirdParty/DetourCrowd/Source/DetourObstacleAvoidance.cpp, Source/ThirdParty/DetourCrowd/Source/DetourPathCorridor.cpp, Source/ThirdParty/DetourCrowd/Source/DetourProximityGrid.cpp, Source/ThirdParty/DetourTileCache/Include/DetourTileCache/DetourTileCache.h, Source/ThirdParty/DetourTileCache/Include/DetourTileCache/DetourTileCacheBuilder.h, Source/ThirdParty/DetourTileCache/Source/DetourTileCache.cpp, Source/ThirdParty/DetourTileCache/Source/DetourTileCacheBuilder.cpp, Source/ThirdParty/Recast/Include/Recast/Recast.h, Source/ThirdParty/Recast/Include/Recast/RecastAlloc.h, Source/ThirdParty/Recast/Source/Recast.cpp, Source/ThirdParty/Recast/Source/RecastContour.cpp, Source/ThirdParty/Recast/Source/RecastMesh.cpp, Source/ThirdParty/Recast/Source/RecastMeshDetail.cpp, Source/ThirdParty/Recast/Source/RecastRasterization.cpp, Source/ThirdParty/Recast/Source/RecastRegion.cpp
Upgrade to recast / detour version from 12/2022 with additional navigation tests (should work with old version also)
There have been some bugfixes and updates in the last few years
=> recast / detour upgrade

Source/Player/Player.cpp
Found an issue with Player when using the --headless flag
=> Fix headless player

Source/Urho3D/Engine/Engine.cpp
With my Server/Client setup using the plugin system I found the need for separate plugin configurations.
=> Add config name to CLI

Source/Urho3D/Graphics/AnimationController.cpp, Source/Urho3D/Graphics/AnimationController.h
=> "Update pose" button in Edtitor

bin/CoreData/Shaders/GLSL/v2/_Config_Material.glsl, bin/CoreData/Shaders/GLSL/v2/_VertexTransform.glsl
=> Missing iTangent fix

Source/Samples/103_GamePlugin/RotateObject.h
The issue where components defined as plugins were not appearing in the editor has been fixed.
=> User component show in editor.

Source/Tests/Urho2D/SpriteSheet2D.cpp, Source/Urho3D/IO/VectorBuffer.cpp, Source/Urho3D/Urho2D/SpriteSheet2D.cpp, Source/Urho3D/Urho2D/SpriteSheet2D.h
SpriteSheet2D can be saved into xml file now.
VectorBuffer GetName() returns AbstractFile::GetName() if set.
=> SpriteSheet2D can be saved into xml file now

Source/Urho3D/Graphics/ModelView.cpp, Source/Urho3D/Graphics/ModelView.h, Source/Urho3D/Graphics/StaticModel.cpp, Source/Urho3D/Graphics/StaticModel.h, Source/Urho3D/Utility/GLTFImporter.cpp
Basically https://github.com/rbfx/rbfx/pull/578 but it also does the suggestions asked.
This is an **API-breaking** change.
=> Change StringVector to ResourceRefList for safer representation of a material list.

bin/CoreData/Shaders/GLSL/v2/M_Refraction.glsl, bin/CoreData/Shaders/GLSL/v2/M_Water.glsl, bin/Data/Scenes/RenderingShowcase_0.xml
Fix for https://github.com/rbfx/rbfx/issues/623
=> Refraction depth fix

Source/Samples/46_RaycastVehicle/RaycastVehicleDemo.cpp, Source/Urho3D/Physics/RaycastVehicle.cpp, Source/Urho3D/SystemUI/Widgets.cpp
=> Raycast Vehicle editor and demo fixes (missing field, int3 widget, etc)

Source/ThirdParty/RmlUi/Include/RmlUi/Core/Context.h, Source/ThirdParty/RmlUi/Include/RmlUi/Core/Element.h, Source/ThirdParty/RmlUi/Include/RmlUi/Core/ElementDocument.h, Source/ThirdParty/RmlUi/Include/RmlUi/Core/ID.h, Source/ThirdParty/RmlUi/Include/RmlUi/Core/Profiling.h, Source/ThirdParty/RmlUi/Include/RmlUi/Core/StyleTypes.h, Source/ThirdParty/RmlUi/Source/Core/Context.cpp, Source/ThirdParty/RmlUi/Source/Core/Element.cpp, Source/ThirdParty/RmlUi/Source/Core/ElementDocument.cpp, Source/ThirdParty/RmlUi/Source/Core/ElementStyle.cpp, Source/ThirdParty/RmlUi/Source/Core/Elements/ElementFormControl.cpp, Source/ThirdParty/RmlUi/Source/Core/Elements/WidgetDropDown.cpp, Source/ThirdParty/RmlUi/Source/Core/Elements/WidgetTextInput.cpp, Source/ThirdParty/RmlUi/Source/Core/Elements/WidgetTextInput.h, Source/ThirdParty/RmlUi/Source/Core/Layout/BlockContainer.cpp, Source/ThirdParty/RmlUi/Source/Core/Layout/BlockFormattingContext.cpp, Source/ThirdParty/RmlUi/Source/Core/Layout/ContainerBox.cpp, Source/ThirdParty/RmlUi/Source/Core/Layout/ContainerBox.h, Source/ThirdParty/RmlUi/Source/Core/Profiling.cpp, Source/ThirdParty/RmlUi/Source/Core/StyleSheetSpecification.cpp
RmlUI Updated to f6d2e787e6c9d38e226d43c860c5c4a7519ca0c9
=> RmlUI Update

Source/Editor/Foundation/ResourceBrowserTab/MaterialFactory.cpp
=> Don't allow to create Unlit PBR materials in editor

Source/Samples/46_RaycastVehicle/RaycastVehicleDemo.cpp
Also added missing debug draw toggle instruction
=> Fix for debug draw output not showing in RaycastVehicleDemo

Source/Urho3D/Network/Network.h, Source/Urho3D/Network/NetworkEvents.h
I'm assuming these are leftovers from deprecated features (NAT punch-through + server password)
=> Minor network cleanup

Source/Editor/Foundation/ConsoleTab.cpp
=> Added menu button to clear the console

Source/Urho3D/Graphics/CubemapRenderer.cpp
Per commit message, cubemap filtering is passing too wayyy many thread-groups.
=> Bug Fix Cubemap Convolution: fix dispatch to send the # of groups

Source/Editor/Foundation/SceneViewTab/SceneScreenshot.cpp
fixed another missing format string in ui::Text
same as https://github.com/rbfx/rbfx/pull/436
=> fixed another missing format string in ui::Text
