rbfx/rbfx

- Source/Urho3D/SystemUI/SystemUI.cpp
> SystemUI: DestroyContext in SystemUI Destructor.

- Directory.Build.props
Works for .Net with Visual Studio 2017.
Does not work with .Net Core as per https://github.com/dotnet/project-system/issues/1125
> Enable Debug Native code by default - C# projects

- Source/Urho3D/Graphics/Batch.cpp
- Source/Urho3D/Graphics/Batch.h
Modify Batch::SortFrontToBack2Pass(..) to accept Batch** iterators instead of entire array.
> Batch:SortFrontToBack2Pass(...)

- Source/ThirdParty/CMakeLists.txt
- Source/ThirdParty/tracy/CMakeLists.txt
Only Add Tracy if URHO3D_NETWORK is enabled.  
Add target type logic to tracy-profiler add_executable(...)
> Tracy-Profiler CMake Fixes

- Docs/Reference.dox
- Source/Urho3D/Core/Context.cpp
- Source/Urho3D/Core/Variant.h
- Source/Urho3D/IO/Deserializer.cpp
- Source/Urho3D/IO/Deserializer.h
- Source/Urho3D/IO/Serializer.cpp
- Source/Urho3D/Resource/JSONValue.cpp
- Source/Urho3D/Resource/JSONValue.h
- Source/Urho3D/Resource/XMLElement.cpp
- Source/Urho3D/Resource/XMLElement.h
- Source/Urho3D/Scene/Serializable.cpp
- Source/Urho3D/Scene/Serializable.h
...for `SharedPtr<Serializable>` object registration as attributes and their serialization in xml/json/binary. At this point multiple references to single object instance would be serialized multiple times and result in multiple new objects when deserialized.
Test sample:
```cpp
class Test : public Serializable
{
URHO3D_OBJECT(Test, Serializable);
public:
Test(Context* context) : Serializable(context)
{
}
static void RegisterObject(Context* context)
{
URHO3D_COPY_BASE_ATTRIBUTES(Serializable);
URHO3D_OBJECT_ATTRIBUTE("My Node Attribute", node_, AM_DEFAULT);
}
SharedPtr<Node> node_;
};
```
```cpp
Test test(context_);
test.node_ = context_->CreateObject<Node>();
test.node_->SetName("foobar");
JSONFile json(context_);
test.SaveJSON(json.GetRoot());
json.SaveFile("/tmp/serializable.json"); …
```
> Scene/IO/Resource: Implement URHO3D_OBJECT_ATTRIBUTE() macro

- Source/Urho3D/IO/Archive.h
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UI.h
On Windows, mouse wheel doesn't work if child is selected even if parent can handle wheel.
I think it's better to redirect wheel into element that can actually handle it, not just nearest "focusable" element.
> Change mouse wheel handling.

- Source/Tools/Editor/Editor.cpp
- Source/Tools/Editor/Inspector/SoundInspector.cpp
- Source/Tools/Editor/Inspector/SoundInspector.h
- Source/Urho3D/Audio/SoundSource.cpp
Adds a minimal sound inspector that just has trivial playback handling along with some basic information.
Changes made to `SoundSource` in order to support using SoundSources without them being attached to Nodes (similar to how `Camera` can be used without a node). Sound playback in the sound inspector is one use case.
> Editor: add Sound Inspector

- bin/CoreData/Shaders/GLSL/AutoExposure.glsl
There is a typo in AutoExposure.glsl.
> Fix sign typo in AutoExposure.glsl

- Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp
I ran into the following log message because I didn't have Graphics Tools installed on my Windows machine:
```
D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
```
Which resulted in this exception:
```
Exception thrown: read access violation.
this->impl_->deviceContext_ was nullptr.
```
https://github.com/rokups/rbfx/blob/f4d90a84fdb6e339f8bbe9ef6d197f2f2a5289f5/Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp#L2213
So I thought: while waiting for it to install, why not make a PR to make sure this only happens for debug builds?
> Only enable DirectX 11 debug mode if URHO3D_DEBUG is active

- Source/Tools/Toolbox/Graphics/SceneView.cpp
I tried rendering the SceneView with a fixed size and realized it wouldn't render unless I forced a size change.
The code in SetSize was never called in the constructor because the rect_ property would be initialized too early. This would prevent the initial setup from happening and for fixed sizes would result in an empty texture.
> Fix SetSize returning too early in constructor

- Source/Urho3D/SystemUI/DebugHud.cpp
Some of the values from ShadowQuality enum are not covered by shadowQualityTexts  array when used in RenderUI method.
This statement:
```cpp
ui::Text("Tex:%s | Mat:%s | Spec:%s | Shadows:%s | Size:%i | Quality:%s | Occlusion:%s | Instancing:%s | API:%s",
//...
shadowQualityTexts[renderer->GetShadowQuality()],
//...
```
Affected by:
```cpp
// Source/Urho3D/Graphics/GraphicsDefs.h
enum ShadowQuality
{
SHADOWQUALITY_SIMPLE_16BIT = 0,
SHADOWQUALITY_SIMPLE_24BIT,
SHADOWQUALITY_PCF_16BIT,
SHADOWQUALITY_PCF_24BIT,
SHADOWQUALITY_VSM,
SHADOWQUALITY_BLUR_VSM
};
```
> Fix out of range bug in DebugHUD when changing shadow quality.

- Source/Urho3D/Resource/BinaryFile.cpp
- Source/Urho3D/Resource/BinaryFile.h
There is no reason to have VectorBuffer as a base type. BinaryFile isn't used as an AbstractFile so it's fine have the VectorBuffer as a field.
Just something I spotted while refactoring AbstractFile.
> Inheritance replaced with composition in BinaryFile

- Source/ThirdParty/SDL/src/audio/SDL_audio.c
While we should normally expect _something_ from the stream based on the
AudioStreamAvailable check, it's possible for a device change to flush the
stream at an inconvenient time, causing this function to return 0.
Thing is, this is harmless. Either data will be NULL and the result won't matter
anyway, or the data buffer will be zeroed out and the output will just be
silence for the brief moment that the device change is occurring. Both scenarios
work themselves out, and testing on Windows shows that this behavior is safe.
> audio: Allow AudioStreamGet to return 0 in RunAudio.

- Source/Tests/Graphics/StaticModel.cpp
- Source/Urho3D/Graphics/CustomGeometry.cpp
- Source/Urho3D/Graphics/Drawable.cpp
- Source/Urho3D/Graphics/Drawable.h
- Source/Urho3D/Graphics/StaticModel.cpp
Having an empty geometry with no vertices is a valid case. For instance a MDL file may have lods where each LOD has it's own material. To implement this scenario only one geometry in each LOD level going to have indices.
> Skip empty geometries

- Source/Samples/SamplesManager.cpp
- Source/Tools/Editor/Editor.cpp
Without this engine only draws a quarter of the window. So "false" value is broken on mac. I suggest to set it to true in order to let mac users to try SamplesManager without troubles.
> Set high dpi to true to make engine to draw the entire window

- Source/Tests/Resource/Graph.cpp
- Source/Urho3D/Resource/Graph.cpp
- Source/Urho3D/Resource/Graph.h
- Source/Urho3D/Resource/GraphNode.cpp
- Source/Urho3D/Resource/GraphNode.h
- Source/Urho3D/Resource/GraphPin.cpp
- Source/Urho3D/Resource/GraphPin.h
- Source/Urho3D/Resource/Resource.cpp
Bug fixed in the graph. Unit tests updated to validate access to connected nodes.
To keep ParticleGraph as close as possible to plain data structure the new GraphPinRef is introduced. It encapsulates Node+Pin pair in a single structure to keep reference to a pin of particular node.
Tested on particle graph.
> GraphPinRef

- Source/Tools/Editor/Project.cpp
New project created in editor should have Data folder to match default engine folder settings.
> Editor Data folder instead of Resources

- Source/Urho3D/RenderPipeline/PostProcessPass.cpp
- Source/Urho3D/RenderPipeline/RenderBufferManager.cpp
We already report on missing resources to the log so there is no need to crash application here.
> pipelineState_ could be null if shader is missing

- bin/CoreData/Shaders/GLSL/v2/_Material_Pixel_Fill.glsl
screenPos is only defined in structure when 
#if defined(URHO3D_REFLECTION_MAPPING) && defined(URHO3D_MATERIAL_HAS_PLANAR_ENVIRONMENT)
> Terrain shader bug fix

- Source/Urho3D/IO/FileSystem.cpp
UWP doesn't report for root directories to exist and hence it doesn't allow to create them.
> CreateDirsRecursive UWP bug fix

- Source/Urho3D/CMakeLists.txt
Previous expression had issues with config names that ended in digits. More specifically, the `URHO3D_D3D11` config that ended in `1`. Which resulted in `URHO3D_D3D11` without the `=1` appended to it. Causing the next config name to be dumped around the initial config name. Example:
```cpp
// Engine configuration
#ifndef URHO3D_D3D11
URHO3D_DEBUG_ASSERT
URHO3D_DEBUG_ASSERT 1
#endif
#ifndef URHO3D_ENABLE_ALL
//...
```
From what I could test. The new expression was able to handle a wild array of cases. And when collapsing, only the last value is kept. Which happens to be the one appended manually. Example:
```cpp
TEST=2323=232=21;
```
Becomes:
```cpp
TEST=21;
```
Except in out case its `=1` mostly.
> Fix regex expression that collapses =1 in config.

- Source/Tests/IO/ConfigFile.cpp
- Source/Urho3D/IO/ConfigFile.cpp
Config file root element should be array.
If parsing config file throws it should return false and not crash the app.
> Less verbose and more robust config files

- Source/Tests/CSharp/Graphics/OutlineGroupTests.cs
- Source/Tests/CSharp/Urho3DNet.Tests.csproj
- Source/Urho3D/CSharp/Managed/Scene/Node.cs
- Source/Urho3D/CSharp/Swig/Urho3D.i
- Source/Urho3D/Graphics/OutlineGroup.cpp
- Source/Urho3D/Graphics/OutlineGroup.h
- .net wrapper fixed
- add/remove should return true in case of success to track what components already present in the collection
- GetParentComponent generic variation
- .net unit test for OutlineGroup
> Outline group .net fix

- Source/Urho3D/RmlUI/RmlUI.h
This helps developers check if the mouse is hovering over a RmlUI window and prevent any things such as ray casts triggering.
> Expose IsHovered

- Source/Urho3D/Physics/PhysicsWorld.h
Addresses the following warning:
```
ThirdParty\Bullet\Bullet\LinearMath\btScalar.h(133,1): warning C4005: 'BT_USE_SSE': macro redefinition
ThirdParty\Bullet\Bullet\LinearMath\btScalar.h(133,1): message : 'BT_USE_SSE' previously declared on the command line
```
> Disable macro redefinition warning

- Source/Editor/Editor.cpp
- Source/Editor/Editor.h
- Source/ThirdParty/CMakeLists.txt
- Source/ThirdParty/enkiTS/.gitignore
- Source/ThirdParty/enkiTS/CMakeLists.txt
- Source/ThirdParty/enkiTS/License.txt
- Source/ThirdParty/enkiTS/README.md
- Source/ThirdParty/enkiTS/src/LockLessMultiReadPipe.h
- Source/ThirdParty/enkiTS/src/TaskScheduler.cpp
- Source/ThirdParty/enkiTS/src/TaskScheduler.h
- Source/Urho3D/CMakeLists.txt
- Source/Urho3D/CSharp/Swig/Urho3D.i
- Source/Urho3D/CSharp/Swig/generated/Urho3D/_pre_core.i
- Source/Urho3D/Core/WorkQueue.cpp
- Source/Urho3D/Core/WorkQueue.h
- Source/Urho3D/Engine/Engine.cpp
- Source/Urho3D/Graphics/Drawable.cpp
- Source/Urho3D/Graphics/Drawable.h
- Source/Urho3D/Graphics/OcclusionBuffer.cpp
- Source/Urho3D/Graphics/Octree.cpp
- Source/Urho3D/Graphics/View.cpp
- Source/Urho3D/RenderPipeline/BatchCompositor.cpp
- Source/Urho3D/RenderPipeline/DrawableProcessor.cpp
- Source/Urho3D/Scene/Scene.cpp
- Source/Urho3D/Urho2D/Renderer2D.cpp
- Source/Urho3D/Urho2D/Renderer2D.h
Changes:
- Most of existing code should still work (with deprecated WorkQueue API)
- `TaskPriority` enum is added with 5 priorities.
- Highest/High/Medium/Low priorities are just priorities, nothing special.
- Immediate priority tasks **must** be waited for, and they will run first of course.
- Therefore, the most common exiting use case is supported:
```
for (...)
queue->AddWorkItem(task, M_MAX_UNSIGNED);
queue->Complete(M_MAX_UNSIGNED);
```
or 
```
for (...)
queue->PostTask(task, TaskPriority::Immediate);
queue->CompleteImmediateForThisThread();
```
- You can wait for completion for *all* tasks.
- You *cannot* wait for completion for all tasks of specified priority anymore.
- API for task dependencies and waiting for specified task is planned at some point.
- You can post the task to …
> Move WorkQueue to enkiTS

- Source/Urho3D/Engine/Engine.cpp
Game will still try to divide time per maxFps so maxFps should never be 0. By fact, it caused a crash on iOS.
> Fix frame limiter

- Source/Urho3D/Graphics/Technique.cpp
- Source/Urho3D/Graphics/Technique.h
- Source/Urho3D/RenderPipeline/PipelineStateBuilder.cpp
Ability to disable colorwrite is necessary for making small depth pre-passes on clusters of geometry
> Added colorwrite property to Pass

- Source/Urho3D/SystemUI/SystemUI.cpp
SystemUI::AddFont() isn't working properly, as in SystemUI::ReallocateFontTexture() first the atlas for new font is allocated, and then the texture which holds the glyphs is immediately destroyed. It seems that the correct order or calls should be:
- Invalidate the cache via ClearPerScreenFonts()
- Create the atlas for new font
> Fixed bug in SystemUI::AddFont() / SystemUI::ReallocateFontTexture()

- Source/Urho3D/Scene/PrefabReference.cpp
- Source/Urho3D/Scene/PrefabReference.h
Introduced new parameter to PrefabReference::SetPrefab(): instanceFlags, which allows the instantiated prefab to appear in game the same as it appears in Editor. instanceFlags controls, which attributes of the root prefab node is copied to the scene node, associated with prefab instance.
> Prefab instancing flags

- Source/Samples/CMakeLists.txt
- Source/Samples/SamplesManager.cpp
XCode will put resources with this specific property into a bundle's subfolder Resources in the bundle. The fix is
1. Adding a property Resources to Data and CoreData folders so they would appear in the resulting bundle
2. Fix paths set into the engine as they must contain the Resources subfolder.
In my past experience, changing engine resource paths did not affect the application functionality.
According to Gleb, such change requires a deep review.
> Add resources to mac os bundle correctly

- Source/Urho3D/Graphics/AnimatedModel.cpp
- Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp
- Source/Urho3D/Graphics/Graphics.cpp
- Source/Urho3D/Graphics/Graphics.h
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
* Added Grphics::SetMaxBones(unsigned) which sets the max limit of HW skinned bones. Do not use values greater than 330, it may cause issues later.
* Addad a warning when model is skinned on CPU due to bone count being too high
> Allows to have hardware skinned models with bone count > 128

- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UIBatch.cpp
In issue #566 all consecutive custom materials in UI was treated as one. That's no longer the case.
Probably some more optimizations can be added, if two different UI materials have exactly the same parameters
> Solves the issue #566

- Source/Urho3D/UI/SplashScreen.h
- Source/Urho3D/UI/TextRenderer3D.h
If you import SplashScreen header without Scene header, an error of C2027 will occurs at build time.
This fix will solve this problem by adding Scene header into SplashScreen header.
See the error in picture above:
There are other headers that have the same problem:
- UI/TextRenderer3D.h
> WIP: fix: error C2027: use of undefined type 'Urho3D::Scene'

- bin/CoreData/Shaders/GLSL/v2/DeferredLight.glsl
Fix for deferred lighting GLSL compilation failure due to vec3/vec4 assignment mismatch
> Fix for deferred lighting GLSL compilation failure due to vec3/vec4 

- Source/Samples/120_HelloVR/HelloVR.cpp
- Source/Urho3D/XR/OpenXR.cpp
- Source/Urho3D/XR/VirtualReality.h
- bin/CoreData/XR/DefaultManifest.xml
See title. Main change is that hands/aims aren't treated as special when updating tracking, all pose actions are located if they are actively bound. Aside from this, all other matters related to hands/aims are unaffected.
> Support for Vive Trackers

- Source/Urho3D/Container/Ptr.h
Changes an std::move to ea::move.
> Fix typo in Ptr.h

- Source/Urho3D/IO/ArchiveSerializationBasic.h
RmlUIComponent currently requires that size.x_ == size.y_ for the render texture size, which causes stretching on non-square render areas.
> Remove requirement of square texture in RmlUICanvasComponent

- Source/Urho3D/SystemUI/StandardSerializableHooks.cpp
Camera preview now works even if camera isn't at root node.
> Camera preview fix

- Source/ThirdParty/crunch/include/crunch/crn_decomp.h
- Source/ThirdParty/libdatachannel/src/impl/wshandshake.hpp
Hey!
I'm having problems to build engine with gcc.
I solved it by adding header files in two places.
The problem places were here:
[1.txt](https://github.com/rbfx/rbfx/files/13689204/1.txt)
[2.txt](https://github.com/rbfx/rbfx/files/13689207/2.txt)
I don't know how correct it is to edit third-party engine's libraries. At least for the sake of history then.
> add headers for gcc

- Source/Samples/106_BakedLighting/BakedLighting.cpp
- Source/Samples/15_Navigation/Navigation.cpp
- Source/Samples/39_CrowdNavigation/CrowdNavigation.cpp
- Source/Tests/Navigation/Navigation.cpp
- Source/Urho3D/Navigation/CrowdAgent.cpp
- Source/Urho3D/Navigation/DynamicNavigationMesh.cpp
- Source/Urho3D/Navigation/DynamicNavigationMesh.h
- Source/Urho3D/Navigation/NavigationDefs.h
- Source/Urho3D/Navigation/NavigationMesh.cpp
- Source/Urho3D/Navigation/NavigationMesh.h
- Source/Urho3D/Navigation/NavigationUtils.cpp
- Source/Urho3D/Navigation/NavigationUtils.h
Fixed-size `(Dynamic)NavigationMesh` should behave almost the same as before.
However, it's not required to know the total dimenstions of the navigation mesh anymore. It can be partially built on demand as long as maximum number of loaded tiles is below the threshold.
This way, it's possible to use navigation system for arbitrarily large worlds. User will have to deal with building, loading and unloading parts of navigation mesh, of course. `Navigation` and `CrowdNavigation` samples may serve as example.
Full list of changes:
- Navigation data format has changed, all previously stored navigation data should be discarded and meshes re-baked. There should be no crashes when loading old data tho.
- Some function renames: `Rebuild` rebuilds entire navigation mesh and deduces maximum number of …
> Refactor navigation mesh design.

- Source/Urho3D/Graphics/Material.cpp
- Source/Urho3D/Graphics/Material.h
Copy operation is required for material pool. Material pool is required while we don't have per-drawable shader parameters and have to use a copy of material to animate properties independently.
@eugeneko any plans on adding per-drawable shader parameters?
> Copy material attributes

- Source/Urho3D/Input/MoveAndOrbitController.cpp
The MoveAndOrbitController has it hard-coded to the default input map file.
> Fixed MoveAndOrbitController not being able to set custom input maps.

- Source/Samples/17_SceneReplication/SceneReplication.cpp
- Source/Samples/17_SceneReplication/SceneReplication.h
The change also updates the overlay to default/0 values when disconnected, before it would keep showing the last set values.
> Added more on screen info to scene replication sample

- Source/Tests/CSharp/Scene/Node.cs
- Source/Urho3D/CSharp/CodeGenerator/CodeGenerator.cs
- Source/Urho3D/CSharp/Managed/Core/Context.cs
- Source/Urho3D/CSharp/Managed/Core/Object.cs
- Source/Urho3D/CSharp/Managed/Core/ObjectReflection.cs
- Source/Urho3D/CSharp/Managed/DerivedFromAttribute.cs
- Source/Urho3D/CSharp/Managed/Resource/ResourceCache.cs
- Source/Urho3D/CSharp/Managed/Scene/Component.cs
- Source/Urho3D/CSharp/Managed/Scene/Node.cs
- Source/Urho3D/CSharp/Managed/UI/UIElement.cs
- Source/Urho3D/CSharp/Swig/Urho3D.i
New ObjectReflection<T> stores a cached value of TypeId from GetStaticType() method. This allows non-trivial naming for the types (for example type names that include namespace on c++ side).
Attribute [DerivedFrom] includes interfaces into type search. This is useful for components that implement multiple interfaces in c#.
[Preserve] attribute automatically injected into all c# Urho3DNet Object classes to ensure Scene deserialization even if game code is compiled ahead-of-time (iOS/Web).
> Use cached TypeId from static method to resovle types

- Source/Urho3D/Core/Timer.h
> Default arg of Timer::Get_Sec() now defaults to false since it's the common case

- Source/Urho3D/Input/MoveAndOrbitComponent.cpp
- Source/Urho3D/Input/MoveAndOrbitController.cpp
These components don't show up in the editor component creation context menu if they don't belong to a category. I just picked the logic category since they are LogicComponents, maybe there is a better fit.
> Added MoveAndOrbit components to a category

- Source/Samples/43_HttpRequestDemo/HttpRequestDemo.cpp
- Source/Urho3D/Network/HttpRequest.cpp
- Source/Urho3D/Network/HttpRequest.h
- Source/Urho3D/Network/Network.cpp
- Source/Urho3D/Network/Network.h
The `Network` subsystem and `HttpRequest` should be de-coupled so that projects can opt in/out of using either one if they need to.
This PR doesn't achieve this but it's the first step towards doing it. I have already decoupled these in my fork since I have a project that uses http but not `Network/Replica`.
I'll wait for feedback before proceeding with the rest.
> Removed Network::MakeHttpRequest()

- Source/Samples/43_HttpRequestDemo/HttpRequestDemo.cpp
- Source/Urho3D/Network/HttpRequest.cpp
- Source/Urho3D/Network/HttpRequest.h
Added this because I needed it, any projects using http likely would too e.g. handling specific api error codes, avoiding re-downloading cached content with code 304 etc.
> Added HttpRequest::GetStatusCode()

- CMake/Modules/UrhoOptions.cmake
- Source/ThirdParty/FreeType/src/gzip/ftzconf.h
- update embree to 3.13.5, and fix this: https://github.com/RenderKit/embree/commit/cda4cf191
- URHO3D_SSE OFF under MacOS Silicon.
- #include <MacTypes.h> in FreeType/src/gzip/ftzconf.h under MacOS Silicon.
> work well under MacOS with Silicon Arm CPU.
